#!/bin/bash

# Функция для создания таблицы смещений
function create_shift_table {
    local pattern=$1
    local pattern_length=${#pattern}

    # Создаем ассоциативный массив для хранения таблицы смещений
    declare -A shift_table

    # Инициализируем таблицу смещений
    for (( i=0; i<$pattern_length; i++ )); do
        shift_table[${pattern:$i:1}]=$(( $pattern_length - $i - 1 ))
    done

    # Возвращаем таблицу смещений
    echo "${shift_table[@]}"
}

# Функция для поиска подстроки в строке с использованием алгоритма Боуера-Мура
function boyer_moore_search {
    local string=$1
    local pattern=$2
    local string_length=${#string}
    local pattern_length=${#pattern}

    # Создаем таблицу смещений
    local shift_table=$(create_shift_table $pattern)

    # Инициализируем переменные
    local i=$pattern_length
    local j=$pattern_length

    # Пока не достигнут конец строки
    while (( $i <= $string_length )); do
        # Если символы совпадают, продолжаем двигаться влево
        if [[ ${string:$i-1:1} == ${pattern:$j-1:1} ]]; then
            (( i-- ))
            (( j-- ))

            # Если найдено полное совпадение, выводим позицию
            if (( $j == 0 )); then
                echo "Найдено вхождение на позиции $i"
                (( i += $pattern_length + 1 ))
                (( j = $pattern_length ))
            fi
        else
            # Получаем смещение из таблицы смещений
            local shift=${shift_table[${string:$i-1:1}]}
            (( i += $pattern_length - min($j, 1 + $shift) ))
            (( j = $pattern_length ))
        fi
    done
}


text=$1
pattern=$2
echo "Строка: $text"
echo "Искомая последовательность: $pattern"
boyer_moore_search $text $pattern
