#!/bin/bash

# Функция для создания таблицы сдвигов
create_shift_table() {
    local pattern=$1
    local m=${#pattern}
    local i
    local j
    declare -A shift_table

    for ((i=0; i<m-1; i++)); do
        shift_table[${pattern:i:1}]=$((m - $i - 1))
    done

    echo "${!shift_table[@]}:${shift_table[@]}"
}

# Функция для поиска всех вхождений подстроки в строку с использованием алгоритма Боуера-Мура
boyer_moore() {
    local text=$1
    local pattern=$2
    local n=${#text}
    local m=${#pattern}
    local shift_table
    local i
    local j

    shift_table=$(create_shift_table $pattern)
    IFS=':' read -r -a keys <<< "$shift_table"
    IFS=':' read -r -a values <<< "${shift_table#*:}"

    i=$((m - 1))
    while [[ $i -lt $n ]]; do
        j=$((m - 1))

        while [[ ${text:i:1} == ${pattern:j:1} ]]; do
            if [[ $j -eq 0 ]]; then
                echo "Подстрока найдена в позиции $((i - m + 1))"
                break
            fi

            i=$((i - 1))
            j=$((j - 1))
        done

        if [[ $j -eq 0 ]]; then
            i=$((i + m))
        else
            i=$((i + ${values[${text:i:1}]}))
        fi
    done
}

text=$1
pattern=$2
echo "Строка: $text"
echo "Искомая последовательность: $pattern"
boyer_moore $text $pattern
